---
- hosts: all
  become: true
  tasks:
  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl

  - name: Disable automatic updates for k8s binaries
    dpkg_selections:
      name: "{{ item }}"
      selection: hold
    loop:
      - kubelet 
      - kubeadm 
      - kubectl

    - name: Delete /etc/containerd/config.toml
    file:
      state: absent
      path: /etc/containerd/config.toml

  - name: Restart containerd
    service:
      name: containerd
      daemon_reload: yes
      state: restarted

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted