# Sets cgroupdriver to systemd
# I think this is the default behavior anyway
# but the instructions say you should do it

# File will be passed with the --config flag during 
# kubeadm init --config kubeadm-config.yaml

# Kubeadm will set this behavior on all nodes when they join
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
localAPIEndpoint:
  advertiseAddress: 192.168.10.160
  bindPort: 6443
nodeRegistration:
  criSocket: "unix:///var/run/crio/crio.sock"
---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.24.2
controlPlaneEndpoint: k8sapi.master.net:4200
networking:
  podSubnet: 10.244.0.0/24
  serviceSubnet: 10.96.0.0/12
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd