---
- hosts: main_master
  become: true
  tasks:
  - name: Copy config file
    copy: src=./kubeadm-config.yaml dest=/tmp/kubeadm-config.yaml mode=0777

  - name: Copy config file for keepalived
    copy: src=./keepalived.conf dest=/etc/keepalived/keepalived.conf

  - name: Copy check script for keepalived
    copy: src=./check_apiserver.sh dest=/etc/keepalived/check_apiserver.sh

  - name: Copy manifest for keepalived
    copy: src=./keepalived.yaml dest=/etc/kubernetes/manifests/keepalived.yaml

  - name: Copy config file for haproxy
    copy: src=./haproxy.cfg dest=/etc/haproxy/haproxy.cfg

  - name: Copy manifest for haproxy
    copy: src=./haproxy.yaml dest=/etc/kubernetes/manifests/haproxy.yaml

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --config /tmp/kubeadm-config.yaml --upload-certs
    register: init_output

  - name: Register init output to local file
    local_action: copy content="{{ init_output.stdout_lines[0] }}" dest="./init_output.txt"

  - name: Setup kubeconfig for aprodromou user
    command: "{{ item }}"
    with_items:
      - mkdir -p /home/aprodromou/.kube
      - cp /etc/kubernetes/admin.conf /home/aprodromou/.kube/config
      - chown aprodromou:aprodromou /home/aprodromou/.kube/config

  - name: Install calico operator on cluster
    become: false
    command: kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml

  - name: Copy custom-resources file for calico CNI
    copy: src=./custom-resources.yaml dest=/tmp/custom-resources.yaml mode=0777

  - name: Install calico custom resources
    become: false
    command: kubectl create -f /tmp/custom-resources.yaml
  
  - name: Taint master nodes
    become: false
    command: "kubectl taint nodes --all node-role.kubernetes.io/master-"

  # - name: Generate join command
  #   command: kubeadm token create --print-join-command
  #   register: join_command

  # - name: Copy join command to local file
  #   local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="/tmp/join-command"
